### ISSUE TITLE
TypeError: __init__() missing 2 required positional arguments: 'id' and 'type'

### ISSUE THREAD

**Issue by cr-MeroujanAntonyan** [swimlane/pyattck#138]
**Describe the bug**
Latest version installed, example snipped is throwing an exception

**Code**
```
from pyattck import Attck

attack = Attck()

for technique in attack.enterprise.techniques:
    print(technique.id)
    print(technique.name)
    for subtechnique in technique.techniques:
        print(subtechnique.id)
        print(subtechnique.name)
```

**Exception**
```
Traceback (most recent call last):
  File "/Users/.../PycharmProjects/scripting/test.py", line 5, in <module>
    for technique in attack.enterprise.techniques:
  File "/Users/.../PycharmProjects/scripting/venv/lib/python3.9/site-packages/pyattck/attck.py", line 255, in enterprise
    from .enterprise import EnterpriseAttck
  File "/Users/.../PycharmProjects/scripting/venv/lib/python3.9/site-packages/pyattck/enterprise.py", line 7, in <module>
    class EnterpriseAttck(Base):
  File "/Users/.../PycharmProjects/scripting/venv/lib/python3.9/site-packages/pyattck/enterprise.py", line 44, in EnterpriseAttck
    __nist_controls_json = NistControls(**Base.config.get_data("nist_controls_json"))
TypeError: __init__() missing 2 required positional arguments: 'id' and 'type'
```

**Desktop (please complete the following information):**
 - OS: Linux, MacOS
 - Version 7.1.1

**Context**
Downgrading did not help

**Comment by cr-MeroujanAntonyan** [comment]
The data URLs are returning 403:
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/99473321/233559449-7d11db3a-ac86-404c-bf6a-b36953ec2ee1.png">

This must be the issue. 
RIP automated runs for last night x)

**Comment by nbyt3** [comment]
Also seeing this same issue

**Comment by MSAdministrator** [comment]
Yeah sorry all - I am no longer with Swimlane and don't have access to the data. Some changes they made broke these links.

**Comment by MSAdministrator** [comment]
This should be resolved now. Please reopen if not.
