### ISSUE TITLE
Error when trying to iterate through techniques

### ISSUE THREAD

**Issue by TiiTcHY** [swimlane/pyattck#144]
Describe the bug
when using the example for iterating through the techniques i get the a keyword argument "socks_support"

for technique in attack.enterprise.techniques:
print(technique.id)

TypeError: attrs_init() got an unexpected keyword argument 'socks_support'

To Reproduce

Create a python script with the following code:
from pyattck import Attck
attack = Attck()
for technique in attack.enterprise.techniques:
print(technique.id)
Expected behavior
i would expect a print out of the current MITRE Techniques

currently using pyattck 7.1.2

Error is below: 

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1833357 (char 1833356)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/.../Desktop/Python/MITRE/pyattckdata.py", line 4, in <module>
    for technique in attack.enterprise.techniques:
                     ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyattck/attck.py", line 255, in enterprise
    from .enterprise import EnterpriseAttck
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyattck/enterprise.py", line 7, in <module>
    class EnterpriseAttck(Base):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyattck/enterprise.py", line 45, in EnterpriseAttck
    __attck = MitreAttck(**Base.config.get_data("enterprise_attck_json"))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyattck/configuration.py", line 145, in get_data
    return self._download_url_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pyattck/configuration.py", line 69, in _download_url_data
    return response.json()
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1833357 (char 1833356)

**Comment by avnerduc** [comment]
I get the same

**Comment by pr3s0** [comment]
i get the same
