### ISSUE TITLE
Exception loading attack = Attck()

### ISSUE THREAD

**Issue by nbyt3** [swimlane/pyattck#26]
When trying to instantiate Attck() i am receiving the following errror:

Traceback (most recent call last):
  File "ingest.py", line 412, in <module>
    attack = Attck()
  File "pyattck.py", line 20, in __init__
    self.attck = __MITRE_ATTCK_JSON_URL__
  File "\venv\lib\site-packages\pyattck\pyattck.py", line 36, in attck
    self._attck = requests.get(value).json()
  File "venv\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "Python\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "Python\Python37-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

**Comment by joshswimlane** [comment]
@nbyt3 Can you provide the version of pyattck you are running and tell me if you can reach this URL on the same system you ran into this issue from? ```https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json```

This looks to be an network issue from the provided error.

**Comment by joshswimlane** [comment]
I'm going to close this out @nbyt3 .  Please upgrade to the latest version.  Thanks!
